# action.yml
name: 'KubeHelm'
description: 'Kubernetes deploy by Helm'
branding:
  icon: 'check-square'
  color: 'white'
inputs:
  namespace:  # namespace to deploy
    description: 'namespace to deploy'
    required: true
    default: ''
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'docker://ghcr.io/black-magius/kube-helm:main'
  env:
    kube_helm_deploy_app_version: ""
    kube_helm_deploy_path_to_helm_files: "./.deploy/.chart"
    kube_helm_deploy_chart_tpl_name: "Chart.tpl.yaml"
    kube_helm_deploy_value_tpl_name: "values.tpl.yaml"
    kube_helm_deploy_destination_namespace: ${{ inputs.namespace }}
    kube_helm_deploy_imagePullPolicy: ""
  args:
    - ${{ inputs.namespace }}
    # - ${{ inputs.github-sarif }}
    # - ${{ inputs.optional-flags }}
